# SPDX-License-Identifier: BSD-3-Clause
"""Drive conda through a specific shell, for shell-dependent behaviour only."""

from __future__ import annotations

import shlex
import shutil
from enum import Enum
from typing import TYPE_CHECKING

from .runner import DEFAULT_TIMEOUT, CliRunner

if TYPE_CHECKING:
    import os
    from collections.abc import Mapping

    from .result import CommandResult


class Shell(Enum):
    """A shell conda can be driven through.

    The value is the executable name (resolved on ``PATH``).
    """

    BASH = "bash"
    ZSH = "zsh"
    POWERSHELL = "pwsh"  # cross-platform PowerShell 7+
    WINDOWS_POWERSHELL = "powershell"  # Windows built-in PowerShell 5.x
    CMD = "cmd"

    @property
    def command_flags(self) -> tuple[str, ...]:
        """The flags that make this shell run a command string and exit."""
        if self in (Shell.BASH, Shell.ZSH):
            return ("-c",)
        if self in (Shell.POWERSHELL, Shell.WINDOWS_POWERSHELL):
            return ("-NoProfile", "-Command")
        if self is Shell.CMD:
            return ("/d", "/c")
        raise AssertionError(f"unhandled shell: {self}")

    def is_available(self) -> bool:
        """Return whether this shell's executable is resolvable on ``PATH``."""
        return shutil.which(self.value) is not None


class ShellRunner:
    """Run a command string through a specific :class:`Shell`.

    Returns the same :class:`~conda_e2e.result.CommandResult` as the other
    runners, so assertions are identical regardless of shell. A plain class (not
    a dataclass) for the same reason as :class:`~conda_e2e.runner.CliRunner`: it
    is a behavioural service, not a value object.

    Args:
        shell: Which shell to invoke.
        environ: Environment for the child process (e.g. the sandboxed
            ``CONDA_*`` dict). If None, ``os.environ`` is inherited.
        cwd: Working directory for the child process.

    """

    def __init__(
        self,
        shell: Shell,
        environ: Mapping[str, str] | None = None,
        cwd: str | os.PathLike[str] | None = None,
    ) -> None:
        self.shell = shell
        self._runner = CliRunner(executable=shell.value, environ=environ, cwd=cwd)

    def run(
        self,
        script: str,
        *,
        extra_env: Mapping[str, str] | None = None,
        cwd: str | os.PathLike[str] | None = None,
        stdin: str | None = None,
        timeout: float | None = DEFAULT_TIMEOUT,
    ) -> CommandResult:
        """Run ``script`` in the shell and return the captured result.

        Args:
            script: The command string the shell will run.
            extra_env: Environment overrides merged onto ``environ``.
            cwd: Per-call working directory override.
            stdin: Optional text piped to the shell's standard input.
            timeout: Seconds before the process is killed (None = no limit).

        Returns:
            CommandResult: The exit code and captured stdout/stderr.

        """
        return self._runner.run(
            *self.shell.command_flags,
            script,
            extra_env=extra_env,
            cwd=cwd,
            stdin=stdin,
            timeout=timeout,
        )

    # convenience alias so call sites read like `shell("conda activate base")`
    __call__ = run


def conda_activate_script(
    shell: Shell,
    env: str,
    command: str = "",
    *,
    conda_exe: str = "conda",
) -> str:
    """Build a script that activates conda env ``env`` in ``shell``, then runs ``command``.

    The hook is generated by ``conda_exe`` (pass the conda under test, e.g. the
    ``conda_exe`` fixture) so shell tests exercise that build rather than
    whatever ``conda`` happens to be on ``PATH``. The activation and any
    follow-up ``command`` then go through the ``conda`` shell function the hook
    defines, which already points back to that same build.

    ``env`` is shell-quoted on the POSIX branch so names with spaces or
    metacharacters are safe; ``command`` is interpolated verbatim by design (it
    is a command line, not a single argument). PowerShell/cmd quoting differs and
    is left to the caller.

    Note:
        The exact hook syntax varies by conda version and platform; confirm
        against your conda on first run (cmd may need ``call conda activate``).

    Args:
        shell: The shell the script targets.
        env: Name of the conda environment to activate.
        command: Optional command to run after activation.
        conda_exe: The conda executable used to emit the shell hook.

    Returns:
        str: A command string ready to pass to a :class:`ShellRunner`.

    """
    if shell in (Shell.BASH, Shell.ZSH):
        exe = shlex.quote(conda_exe)
        script = f'eval "$({exe} shell.bash hook)" && conda activate {shlex.quote(env)}'
        return f"{script} && {command}" if command else script
    if shell in (Shell.POWERSHELL, Shell.WINDOWS_POWERSHELL):
        hook = f'(& "{conda_exe}" shell.powershell hook) | Out-String | Invoke-Expression'
        script = f"{hook}; conda activate {env}"
        return f"{script}; {command}" if command else script
    if shell is Shell.CMD:
        script = f'"{conda_exe}" activate {env}'
        return f"{script} && {command}" if command else script
    raise AssertionError(f"unhandled shell: {shell}")  # pragma: no cover
